image: gitpod/workspace-full-vnc
tasks:
  - init: chmod 777 main.sh && ./main.sh
    command: echo hello
ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-preview
vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
    - dracula-theme.theme-dracula